on:
  workflow_call:
    inputs:
      run-name:
        required: false
        description: 'Analisis de código'
        default: 'Running SAST'
        type: string        
name: SAST
run-name: ${{inputs.run-name}}
jobs:
  A_SAST:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: AnálisisSAST
        uses: sonarsource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}