on: 
  workflow_call:
    inputs:
      run-name:
        required: false
        type: string

name: Docker
run-name: ${{inputs.run-name}}

jobs:
  Buid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Docker
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_SECRETS_USER }}
          password: ${{ secrets.DOCKER_SECRETS_PASS }}
  
      - name: Build Docker
        run: |
          docker build --tag iliberona/devsecops:latest .
  
      - name: ImageSecurity
        uses: ./.github/workflows/ci-image-security.yml
          #exit-code: 1 #Si se presentan vulnerabilidades altas o medias, no se realiza el push al repositorio dockerhub. 

      - name: Push Docker
        run: |
          docker push iliberona/devsecops