on:   
  workflow_call:
    inputs:
      run-name:
        required: true
        type: string

name: Clone-repository
run-name: ${{inputs.run-name}}

jobs:  
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repositorio
      uses: GuillaumeFalourd/clone-github-repo-action@v2.1
      with:
        depth: 1
        branch: 'main'
        owner: 'DevSecOps-Ciclo-7'
        repository: 'final-lab'
        
    - name: Acceso al repositorio
      run: |
        cd devsecops
        ls -la
