on:   
  workflow_call:
    inputs:
      run-name:
        required: true
        type: string

name: Clone-repository
run-name: ${{inputs.run-name}}

jobs:  
  Clone:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: GuillaumeFalourd/clone-github-repo-action@v2.1
      with:
        depth: 1
        branch: 'feature'
        owner: 'DevSecOps-Ciclo-7'
        repository: 'final-lab'
        
    - name: Acceso al repositorio
      run: |
        cd final-lab
        ls -la
        cp -R * /
        cd /home/root
        ls -la