on:
  workflow_call:
    inputs:
      run-name:
        required: false
        type: string

name: ScannerImage
run-name: ${{inputs.run-name}}

jobs:
  ImageSecurity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ImageSecurity
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'iliberona/devsecops-final:latest'
          format: 'table'
          #exit-code: 1 #Si se presentan vulnerabilidades altas o medias, no se realiza el push al repositorio dockerhub. 