on:
  workflow_call:
    inputs:
      run-name:
        required: false
        type: string

name: Docker_push
run-name: ${{inputs.run-name}}

jobs:
  Push:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Docker
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_SECRETS_USER }}
          password: ${{ secrets.DOCKER_SECRETS_PASS }}

      - name: Push Docker
      
        run: |
          docker push iliberona/devsecops-final:latest
      - uses: actions/checkout@v4
      