on:
    workflow_call:
      inputs:
        run-name:
          required: false
          type: string

name: Docker_push
run-name: ${{inputs.run-name}}

jobs:
    buid:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
              fetch-depth: 0

        - name: Push Docker
          run: |
             docker push iliberona/devsecops