on:
  workflow_call:
    inputs:
      run-name:
        required: false
        type: string

name: Docker_push
run-name: ${{inputs.run-name}}

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Docker
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_SECRETS_USER }}
          password: ${{ secrets.DOCKER_SECRETS_PASS }}
      
      - name: Push Docker
        run: |
          docker push iliberona/devsecops:latest