on:
  workflow_call:
    inputs:
      run-name:
        required: false
        default: 'Running SAST'
        type: string        
name: analisis-SAST
run-name: ${{inputs.run-name}}

jobs:
  Analisis_SAST:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Análisis-SAST
        uses: sonarsource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}