on:
  workflow_call:
    inputs:
      run-name:
        required: false
        type: string
               
name: Analisis-SCA
run-name: ${{inputs.run-name}}

jobs:
    DCheck:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
              fetch-depth: 0
              
        - name: Dependency Check
          uses: dependency-check/Dependency-Check_Action@main
          with:
            project: 'devsecops-final'
            path: '.'
            format: 'HTML'
            out: 'reports'
            #args: > #argumento para detener pipeline en caso de encontrar vulnerabilidades si identifica vulnerabilidades igual o mayor a 3 falla la ejecucion y genera un reporte
              #--failOnCVSS 3 

        - name: Resultado de reporte
          uses: actions/upload-artifact@master
          with:
             name: Dependency report
             path: ${{github.workspace}}/reports