on:
  workflow_call:
    inputs:
      run-name:
        required: false
        type: string
               
name: DependencyCheck
run-name: ${{inputs.run-name}}

jobs:
  SCA-DCheck:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
              fetch-depth: 0
              
        - name: Dependency Check
          uses: dependency-check/Dependency-Check_Action@main
          with:
            project: 'devsecops'
            path: '.'
            format: 'HTML'
            
        - name: Resultado de reporte
          uses: actions/upload-artifact@master
          with:
             name: Dependency report
             path: ${{github.workspace}}/reports