run-name: main
on:
  push: 
    branches: 
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Vulnerabilidad-SAST:
    uses: ./.github/workflows/ci-template-sast.yml
    with:
      run-name: "mainT"
    secrets: inherit  
