name: CICD
on:
  push:
    branches:
      - main 
  pull_request:
    types: [opened, synchronize, reopened] 
jobs:
    AnalisisSAST:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
              fetch-depth: 0
        - name: Análisis SAST
          uses: sonarsource/sonarcloud-github-action@master
          env:
              GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
    DependencyCheck:
      needs: AnalisisSAST
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
              fetch-depth: 0
              
        - name: Dependency Check
          uses: dependency-check/Dependency-Check_Action@main
          with:
            project: 'devsecops'
            path: '.'
            format: 'HTML'
            
        - name: Reporte de resultados
          uses: actions/upload-artifact@master
          with:
             name: Dependency report
             path: ${{github.workspace}}/reports
             
    Docker_buid_push:
      needs: DependencyCheck
      runs-on: ubuntu-latest
       
      steps:
        - uses: actions/checkout@v4
          with:
              fetch-depth: 0
        - name: Docker
          uses: docker/login-action@v3.0.0
          with:
            username: ${{ secrets.DOCKER_SECRETS_USER }}
            password: ${{ secrets.DOCKER_SECRETS_PASS }}
  
        - name: Build Docker
          run: |
            docker build --tag iliberona/devsecops:latest .
  
        - name: Image Security
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: 'iliberona/devsecops:latest'
            format: 'table'
            exit-code: 1 #Si se presentan vulnerabilidades altas o medias, no se realiza el push al repositorio dockerhub. 
            
        - name: Push Docker
          run: |
            docker push iliberona/devsecops 
  
          #- name: Build and push
          #uses: docker/build-push-action@v5
          #with:
           #push: true
           #tags: iliberona/devsecops:latest
           
    Deploy:
           needs: Docker_buid_push
           runs-on: self-hosted
      
           steps:
      
           - name: Pull Image Docker
             run: |
               docker pull iliberona/devsecops:latest
         
           - name: Liberacion
             run: |
               docker run -p 8085:8085 --name iliberona-deploy -d iliberona/devsecops:latest
 