run-name: Workflow Análisis 

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened] 
jobs:
  SAST:
    uses: ./.github/workflows/ci/template-sast.yml
    with:
      run-name: "Análisis de Código"
    secrets: inherit  