run-name: ${{ github.actor }} CICD 

on:
  push:
    branches:
      - main
      - feature
  pull_request:
    types: [opened, synchronize, reopened] 

jobs:
  Analisis-SAST:
    uses: ./.github/workflows/ci-template-sast.yml
    with:
      run-name: "SAST"
    secrets: inherit
  
  Analisis-SCA:
    uses: ./.github/workflows/ci-template-dcheck.yml
    with:
      run-name: "Dependency Check"
    secrets: inherit  
     
  DockerImage:
    needs: [Analisis-SAST, Analisis-SCA]
    uses: ./.github/workflows/ci-build-docker.yml
    with:
      run-name: "Build Docker"
    secrets: inherit
  
  #ScannerImage:
    #needs: DockerImage
    #uses: ./.github/workflows/ci-image-security.yml
    #with:
      #run-name: "Image Security"
    #secrets: inherit 

  #Docker_push:
    #needs: ScannerImage
    #uses: ./.github/workflows/ci-push-docker.yml
    #with:
      #run-name: "Push Docker"
    #secrets: inherit

  #Deploy:
    #needs: DockerImage
    #uses: ./.github/workflows/cd-deploy-typescript.yml
    #with:
      #run-name: "Deploy"
    #secrets: inherit 