run-name: Build 

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened] 

jobs:
  SAST:
    uses: ./.github/workflows/ci-template-sast.yml
    with:
      run-name: "SAST"
    secrets: inherit
  
  DependencyCheck:
    needs: SAST
    uses: ./.github/workflows/ci-template-dcheck.yml
    with:
      run-name: "Dependency Check"
    secrets: inherit  