run-name: Analisis Sast 

on:
  push:
    branches: 
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Vulnetabilidad-SAST:
    uses: ./.github/workflows/ci-template-sast.yml
    with:
      run-name: "Análisis Sast"
    secrets: inherit  