run-name: Build 

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened] 
    
jobs:
  analisis-SAST:
    uses: ./.github/workflows/ci-template-sast.yml
    with:
      run-name: "Análisis de Código"
    secrets: inherit  